### ISSUE TITLE
InitWorkflow with Shiny

### ISSUE THREAD

**Issue by wheintz** [r-geoflow/geoflow-shiny#6]
Hi @eblondel,

Would it be possible to execute initWorkflow with Shiny, before executing the workflow? We could have an idea of possible issues ...

Thanks!

**Comment by eblondel** [comment]
yes, why not

**Comment by eblondel** [comment]
Relates to https://github.com/eblondel/geoflow/issues/237

**Comment by eblondel** [comment]
This is partially done in #18 for testing the validity of metadata tables.

**Comment by eblondel** [comment]
geoflow logs now include results of `initWorkflow`. When executing a workflow all logs will be included in `job-logs.txt` file, and in geoflow-shiny, all appear interactively in the R console.

**Comment by eblondel** [comment]
@wheintz  see #22 where execution UI was improved. Now you will be able to see 1) the R session info, 2) the initialization, 3) the execution in an interactive way organized in accordion UI, that will be progressively update during the workflow.

In case of a sucessful workflow, all get green like this:

![image](https://user-images.githubusercontent.com/1324396/196105776-6776074d-3e0e-413c-beab-1386f5e21c70.png)

In case the `initialization` fails, it will stop there and appear in red, showing the logs for you to check:

![image](https://user-images.githubusercontent.com/1324396/196106008-b6cb4972-0754-4ae1-b7ca-f8c9081e9754.png)
