### ISSUE TITLE
Shiny left menu

### ISSUE THREAD

**Issue by wheintz** [r-geoflow/geoflow-shiny#8]
Hi @eblondel,

Last issue for today. It's not really an issue, but an ergonomic suggestion:
Would it be possible to make the left menu simpler? The "configuration" expand is not really intuitive for a novice user.

Thank you!

 Wiflried

**Comment by eblondel** [comment]
@wheintz i've made the "configuration" menu expanded by default so users can access directly the sub-menu items. Would it be enough? I let it under a expandable menu, thinking that other menus might come, but we could also have 2 different menus items (without expandable accordion). Let meknow
